// ---------------------------------------------------------------------------
// Datos de ejemplo — sustituir por datos reales del API
// ---------------------------------------------------------------------------
export const cliente = {
    nombre: "DAVID PAULINO VAZQUEZ PADILLA",
    clienteId: "CLC25179",
    telefono: "6677514375",
    genero: "HOMBRE",
    estadoCivil: "SOLTERO (A)",
    escolaridad: "LICENCIATURA",
    ocupacion: "",
    ine: "VZPDDV78011525H700",
    curp: "VAPD780115HSLZDV02",
    rfc: "VAPD780115427",
    pasaporte: "NA",
    credencialImss: "NA",
    fiel: "NA",
    nacionalidad: "MEXICO",
    fechaNacimiento: "1978-01-15",
    paisNacimiento: "MEXICO",
    lugarNacimiento: "CULIACAN",
    entidadNacimiento: "SINALOA",
    domicilio: {
        pais: "MEXICO",
        estado: "SINALOA",
        localidad: "FRACCIONAMIENTO VILLA BONITA",
        asentamiento: "FRACCIONAMIENTO VILLA BONITA",
        tipoVialidad: "CALLE",
        vialidad: "MANUE CLOUTHIER",
        referencia: "NA",
        manzana: "NA",
        lote: "NA",
        numExt: "5991",
        numInt: "NA",
    },
    relaciones: [
        { nombre: "ROSA MARIA ZAVALA UNZUETA", rol: "AVAL", parentesco: "AMIGO(A)" },
    ],
    economicos: {
        ingresos: [
            {
                motivo: "VENTAS DE NEGOCIO",
                descripcion: "VENTAS DIARIAS",
                actividad: "FABRICACION DE HELADOS NIEVES Y PALETAS",
                monto: 189000,
            },
        ],
        egresos: [
            { motivo: "SERVICIOS GENERALES", descripcion: "PAGO PROVEEDORES", monto: 126500 },
        ],
        bancarios: [
            {
                moneda: "PESOS MEXICANOS",
                banco: "BANORTE/IXE",
                cuenta: "1112488070",
                clabe: "072730011124880707",
                tarjeta: "",
            },
        ],
    },
    pld: {
        riesgo: "BAJO RIESGO",
        metodo: "EVALUACION POR PARAMETROS MATRIZ DE RIESGO",
        ultimaOperacion: "2026-01-13 15:19:07.0",
        operacion: "REGISTRO DE CREDITOS",
        valoracion: 0.81,
    },
    producto: {
        creditoId: "26CLC9940",
        ciclo: 1,
        asesor: "MARIA DE LA LUZ SUAREZ FLORES",
        fechaDesembolso: "20-01-2026",
        fechaPrimerPago: "20-02-2026",
        fechaUltimoPago: "05-02-2027",
        estado: "ACTIVO",
        actividadEconomica: "FABRICACION DE HELADOS NIEVES Y PALETAS",
        actividadPersonalizada: "ANTOJOS",
        destinoCredito: "ADQUIRIR O COMPRAR MERCANCIA",
        destinoPersonalizado: "CAPITAL DE TRABAJO",
        origenRecursos: "VENTA DE PRODUCTOS Y SERVICIOS",
        montoSolicitado: 25000,
        montoAutorizado: 25000,
        interes: 2500,
        impuesto: 0,
        categoria: "CREDITO INDIVIDUAL SIN IVA",
        productoFinanciero: "MICROCREDITO 5-25",
        calculoInteres: "SALDOS GLOBALES",
        frecuenciaPagos: "24 QUINCENAL",
        numeroPagos: 24,
        frecuencia: "QUINCENAL",
        tasaAnual: 10.0,
        direccion:
            "MANUE CLOUTHIER, FRACCIONAMIENTO VILLA BONITA, FRACCIONAMIENTO VILLA BONITA, CULIACÁN, SINALOA, CP: 80199",
        coacreditados: [
            {
                nombre: "ROSA MARIA ZAVALA UNZUETA",
                ife: "ZVUNRS53020625M700",
                curp: "ZAUR530206MSLVNS15",
                rfc: "",
                direccion:
                    "ABRAHAM LINCON, COLONIA CHAPULTEPEC, COLONIA CHAPULTEPEC, CULIACÁN, SINALOA, CP: 80040",
                parentesco: "AMIGO(A)",
                tipoRelacion: "AVAL",
            },
        ],
        garantias: 0,
        montosAutorizados: 25000,
        pagos: 0,
        creditosTotales: 1,
    },
    encuestas: [
        {
            titulo: "PERFIL TRANSACCIONAL",
            fecha: "13/01/2026 14:37",
            preguntas: [
                { p: "¿Espera realizar pagos anticipados?", r: "No" },
                { p: "¿Con que frecuencia espera realizar pagos anticipados?", r: "NO" },
                { p: "¿Espera liquidar su crédito dentro de los 3 primeros meses a su otorgamiento?", r: "No" },
                { p: "¿Instrumento monetario con el que desea realizar los pagos anticipados o liquidación de crédito?", r: "Efectivo" },
                { p: "¿Montos esperados de los pagos anticipados?", r: "1000 a 3000" },
            ],
        },
    ],
    listasUIF: {
        consulta: "ILWOVMIWPX",
        fecha: "2026-02-25 15:53:10",
        alerta: true,
        items: [
            "PERSONAS POLITICAMENTE EXPUESTAS",
            "LPB NACIONAL",
            "LPB INTERNACIONAL PERSONAS",
            "LPB INTERNACIONAL ENTIDADES",
            "LISTA OFAC",
            "LISTA PGR",
            "LISTA 69 BIS",
            "PEPS EXTRANJEROS",
            "PEPS Y EMPRESAS OTRO RIESGO",
            "PEPS NAC",
        ],
    },
    criteriosPaises: [
        {
            consulta: "KSGLCHQKLV",
            fecha: "2026-02-25 15:53:10",
            alerta: true,
            items: ["LISTADO PARAISO FISCAL", "PAISES NO COPERANTES", "MEDIDAS DEFICIENTES"],
        },
        {
            consulta: "TERMYWZOQC",
            fecha: "2026-01-13 14:19:07",
            alerta: false,
            items: [],
        },
    ],
    alertasPerfil: [
        {
            tipoAlerta: "PERFIL TRANSACCIONAL",
            nombre: "DAVID PAULINO",
            apellidoPaterno: "VAZQUEZ",
            apellidoMaterno: "PADILLA",
            descripcionOperacion: "PERFIL TRANSACCIONAL",
            descripcionReporte: "EVALUACION POR PARAMETROS MATRIZ DE RIESGO",
            nacionalidad: "MEXICO",
            fechaNacimiento: "14-01-1978",
            direccion: "MEXICO,SINALOA,CULIACÁN,MANUE CLOUTHIER,5991",
            colonia: "MEXICO",
            coloniaLocalidad: "FRACCIONAMIENTO VILLA BONITA",
            curp: "VAPD...",
        },
    ],
    alertasOperacion: [
        {
            empresa: "FATIMA HERNANDEZ ZAVALA",
            localidad: "FRACCIONAMIENTO VILLA BONITA",
            cp: "80199",
            casfim: "",
            tipoOperacion: "OTORGAMIENTO DE CREDITO",
            descripcionOperacion: "PERFIL TRANSACCIONAL",
            instrumento: "",
            numeroContrato: "26CLC9940",
            folio: "CLC10615",
            monto: 25000,
            moneda: "PESOS MEXICANOS",
            fechaOperacion: "2026-01-14 13:01:51",
        },
    ],
};