export const paisesData = [
    { nombre: 'ANDORRA', descripcion: 'ANDORRA', codigo: 'AD', largo: '', cnbv: '50' },
    { nombre: 'ANGUILA', descripcion: 'ANGUILA', codigo: 'AI', largo: '', cnbv: '50' },
    { nombre: 'ARUBA', descripcion: 'ARUBA', codigo: 'AW', largo: '', cnbv: '50' },
    { nombre: 'BAHAMAS', descripcion: 'BAHAMAS', codigo: 'BS', largo: '', cnbv: '50' },
    { nombre: 'BAHREIN', descripcion: 'BAHREIN', codigo: 'BH', largo: '', cnbv: '50' },
    { nombre: 'BARBADOS', descripcion: 'BARBADOS', codigo: 'BB', largo: '', cnbv: '50' },
    { nombre: 'BELICE', descripcion: 'BELICE', codigo: 'BZ', largo: '', cnbv: '50' },
    { nombre: 'BERMUDAS', descripcion: 'BERMUDAS', codigo: 'BM', largo: '', cnbv: '50' },
    { nombre: 'CURAZAO', descripcion: 'CURAZAO', codigo: 'CW', largo: '', cnbv: '50' },
    { nombre: 'DOMINICA', descripcion: 'DOMINICA', codigo: 'DM', largo: '', cnbv: '50' },
    { nombre: 'EMIRATOS ARABES', descripcion: 'EMIRATOS ARABES', codigo: 'AE', largo: '', cnbv: '50' },
    { nombre: 'GIBRALTAR', descripcion: 'GIBRALTAR', codigo: 'GI', largo: '', cnbv: '50' },
    { nombre: 'GUERNSEY', descripcion: 'GUERNSEY', codigo: 'GG', largo: '', cnbv: '50' },
    { nombre: 'HONG KONG', descripcion: 'HONG KONG', codigo: 'HK', largo: '', cnbv: '50' },
    { nombre: 'ISLA DE MAN', descripcion: 'ISLA DE MAN', codigo: 'IM', largo: '', cnbv: '50' },
    { nombre: 'ISLAS CAIMAN', descripcion: 'ISLAS CAIMAN', codigo: 'KY', largo: '', cnbv: '50' },
    { nombre: 'JERSEY', descripcion: 'JERSEY', codigo: 'JE', largo: '', cnbv: '50' },
    { nombre: 'LIECHTENSTEIN', descripcion: 'LIECHTENSTEIN', codigo: 'LI', largo: '', cnbv: '50' },
    { nombre: 'LUXEMBURGO', descripcion: 'LUXEMBURGO', codigo: 'LU', largo: '', cnbv: '50' },
    { nombre: 'MACAO', descripcion: 'MACAO', codigo: 'MO', largo: '', cnbv: '50' },
];