import {
    Bell,
    AlertTriangle,
    Clock,
    FileSearch,
    Eye,
    XCircle,
    CheckCircle,
} from "lucide-react";

export const alertStats = [
    {
        icon: Bell,
        label: "Total Alertas",
        value: 8,
        color: "text-blue-600",
        bgColor: "bg-blue-50",
    },
    {
        icon: AlertTriangle,
        label: "Críticas",
        value: 2,
        color: "text-red-600",
        bgColor: "bg-red-50",
    },
    {
        icon: Clock,
        label: "Pendientes",
        value: 4,
        color: "text-orange-600",
        bgColor: "bg-orange-50",
    },
    {
        icon: FileSearch,
        label: "En Revisión",
        value: 2,
        color: "text-purple-600",
        bgColor: "bg-purple-50",
    },
    {
        icon: Eye,
        label: "Verificadas",
        value: 0,
        color: "text-blue-600",
        bgColor: "bg-blue-50",
    },
    {
        icon: XCircle,
        label: "Bloqueadas",
        value: 0,
        color: "text-gray-600",
        bgColor: "bg-gray-50",
    },
    {
        icon: CheckCircle,
        label: "Resueltas",
        value: 2,
        color: "text-gray-600",
        bgColor: "bg-gray-50",
    },
];

export const initialAlertsData = [
    {
        id: "A001",
        priority: "CRITICA",
        priorityColor: "bg-red-500",
        status: "Pendiente",
        statusColor: "bg-red-100 text-red-800",
        title: "Umbral Transaccional",
        description: "Cliente excedió umbral mensual de $500,000 MXN",
        cliente: "Juan Pérez García",
        clienteId: "C001",
        monto: "$650,000 MXN",
        fecha: "2024-11-24 10:30",
        borderColor: "border-l-red-500",
    },
    {
        id: "A002",
        priority: "ALTA",
        priorityColor: "bg-orange-500",
        status: "En Revisión",
        statusColor: "bg-yellow-100 text-yellow-800",
        title: "Coincidencia Lista PEP",
        description: "Coincidencia del 95% con registro en Lista PEP",
        cliente: "María González",
        clienteId: "C003",
        monto: "N/A",
        fecha: "2024-11-24 09:15",
        borderColor: "border-l-orange-500",
    },
    {
        id: "A003",
        priority: "MEDIA",
        priorityColor: "bg-yellow-500",
        status: "Pendiente",
        statusColor: "bg-red-100 text-red-800",
        title: "Perfil Inusual",
        description:
            "Patrón de operaciones diferente al perfil transaccional declarado",
        cliente: "Empresa XYZ SA",
        clienteId: "C002",
        monto: "$250,000 MXN",
        fecha: "2024-11-23 16:45",
        borderColor: "border-l-yellow-500",
    },
    {
        id: "A004",
        priority: "ALTA",
        priorityColor: "bg-orange-500",
        status: "Resuelta",
        statusColor: "bg-green-100 text-green-800",
        title: "Operación en Efectivo",
        description: "Operación en efectivo superior a $100,000 MXN",
        cliente: "Carlos Ramírez",
        clienteId: "C005",
        monto: "$150,000 MXN",
        fecha: "2024-11-23 14:20",
        borderColor: "border-l-orange-500",
    },
    {
        id: "A005",
        priority: "CRITICA",
        priorityColor: "bg-red-500",
        status: "En Revisión",
        statusColor: "bg-yellow-100 text-yellow-800",
        title: "Múltiples Transacciones Fragmentadas",
        description: "Patrón de fragmentación para evitar detección",
        cliente: "Roberto Silva",
        clienteId: "C008",
        monto: "$890,000 MXN",
        fecha: "2024-11-22 11:30",
        borderColor: "border-l-red-500",
    },
    {
        id: "A006",
        priority: "MEDIA",
        priorityColor: "bg-yellow-500",
        status: "Pendiente",
        statusColor: "bg-red-100 text-red-800",
        title: "Cliente de Alto Riesgo",
        description: "Actividad inusual en cuenta de alto riesgo",
        cliente: "Imports Global SA",
        clienteId: "C012",
        monto: "$425,000 MXN",
        fecha: "2024-11-22 09:00",
        borderColor: "border-l-yellow-500",
    },
    {
        id: "A007",
        priority: "ALTA",
        priorityColor: "bg-orange-500",
        status: "Pendiente",
        statusColor: "bg-red-100 text-red-800",
        title: "Transferencias Internacionales Sospechosas",
        description: "Múltiples transferencias a paraísos fiscales",
        cliente: "Tech Solutions Inc",
        clienteId: "C015",
        monto: "$1,200,000 MXN",
        fecha: "2024-11-21 15:45",
        borderColor: "border-l-orange-500",
    },
    {
        id: "A008",
        priority: "MEDIA",
        priorityColor: "bg-yellow-500",
        status: "Resuelta",
        statusColor: "bg-green-100 text-green-800",
        title: "Cambio Repentino de Comportamiento",
        description: "Incremento significativo en volumen de operaciones",
        cliente: "Laura Martínez",
        clienteId: "C018",
        monto: "$180,000 MXN",
        fecha: "2024-11-21 10:20",
        borderColor: "border-l-yellow-500",
    },
];

export const alertTypesConfig = [
    {
        id: "umbral-transaccional",
        title: "Umbral Transaccional",
        description: "Excede límite de operaciones mensuales",
    },
    {
        id: "coincidencia-pep",
        title: "Coincidencia PEP",
        description: "Coincidencia en Lista PEP",
    },
    {
        id: "listas-negras",
        title: "Coincidencia Listas Negras",
        description: "Coincidencia en listas OFAC, ONU, UE",
    },
    {
        id: "perfil-inusual",
        title: "Perfil Inusual",
        description: "Operaciones fuera del perfil transaccional",
    },
    {
        id: "operacion-efectivo",
        title: "Operación en Efectivo",
        description: "Operaciones en efectivo superiores al umbral",
    },
    {
        id: "pais-alto-riesgo",
        title: "País de Alto Riesgo",
        description: "Operaciones con países de alto riesgo",
    },
    {
        id: "transacciones-fragmentadas",
        title: "Transacciones Fragmentadas",
        description: "Patrón de fragmentación sospechoso",
    },
    {
        id: "cliente-alto-riesgo",
        title: "Cliente Alto Riesgo",
        description: "Actividad inusual en cuentas de alto riesgo",
    },
    {
        id: "transferencias-internacionales",
        title: "Transferencias Internacionales Sospechosas",
        description: "Múltiples transferencias a paraísos fiscales",
    },
    {
        id: "cambio-comportamiento",
        title: "Cambio Repentino de Comportamiento",
        description: "Incremento significativo en volumen de operaciones",
    },
];

export const STATUS_STYLES = {
    Pendiente: { statusColor: "bg-red-100 text-red-800" },
    "En Revisión": { statusColor: "bg-yellow-100 text-yellow-800" },
    Resuelta: { statusColor: "bg-green-100 text-green-800" },
    Verificado: {
        statusColor: "bg-blue-100 text-blue-800",
        borderColor: "border-l-blue-500",
    },
    Bloqueado: {
        statusColor: "bg-gray-100 text-gray-800",
        borderColor: "border-l-gray-500",
    },
};